### ISSUE TITLE
Support pan/scroll in overview pane

### ISSUE THREAD

**Issue by peter-dolkens** [kubevious/kubevious#10]
**Is your feature request related to a problem? Please describe.**
I instinctively try to use my track-pad to scroll around in the overview pane, instead of using the click-and-drag navigator.

**Describe the solution you'd like**
I'd like the navigation pane to pan and scroll when using my track-pad. When using a mouse, scrolling should scroll, and alt+scrolling or ctrl+scrolling should pan.

**Describe alternatives you've considered**
There is already a navigator implemented, but that is not a completely natural UX, especially when expanding nodes near the bottom of the screen.

**Comment by rubenhak** [comment]
@peter-dolkens, thanks for suggestion. That definitely can be done, but the only problem i see is that scrolling left on the trackpad causes the browser to go back to preview page.

**Comment by peter-dolkens** [comment]
Pretty sure there’s libraries out there for that, as it works on google maps for example. Might need some scroll bar trickery to achieve it.

Don’t forget touch screens (tablets and laptops) either - though that one just should just be a drag/drop.

Peter Dolkens

**Comment by rubenhak** [comment]
In google maps panning up/down does zooming, but left/right still causes browser to go back/forward in history. 

Anyway, will try to find some way to improve navigation usability.

**Comment by peter-dolkens** [comment]
Ah you're right - google maps does zoom and forward/back on the trackpad.

Here's a site that does pan+scroll: https://www.photopea.com/ - just open the demo.psd, zoom in, then you can pan and scroll to your hearts desire.

**Comment by rubenhak** [comment]
@peter-dolkens, wonderful, if photopea did it, we can do that as well!

**Comment by rubenhak** [comment]
@peter-dolkens, here is what was done:
1. Panning with mouse works over the entire "Universe" area. No need to drag boxes. Can be initiated by dragging from empty area as well.
2. Can pan using regular scroll wheel by standard means. Up/down using scroll wheel, left/right using Shift-wheel.
3. Sliding trackpad within the "Universe" area. History navigation should be prevented when two fingers swiped with the area. Outside default behavior should persist.

Please try it out in the live demo and let me know how it works for you: https://demo.kubevious.io/

**Comment by rubenhak** [comment]
@peter-dolkens temporarily assigning to you to give feedback on the changes

**Comment by peter-dolkens** [comment]
Will try this when I wake up in the morning - sounds good!

**Comment by peter-dolkens** [comment]
Works exactly as expected on my touch-enabled laptop - lovely UX =D

**Comment by rubenhak** [comment]
Wonderful! Will be released along with few other improvements soon.

Sadly there is not too much real estate available to show what in the navigation window. Need to spend some more time on guiding users towards problematic areas.

No plans for pinch-to-zoom, but might go straight to VR/AR :D

**Comment by peter-dolkens** [comment]
> Sadly there is not too much real estate available to show what in the navigation window. Need to spend some more time on guiding users towards problematic areas.

I was thinking something like this could help:
![image](https://user-images.githubusercontent.com/469666/77715656-125c2500-6fd4-11ea-9b44-06488ad244f1.png)

**Comment by rubenhak** [comment]
> I was thinking something like this could help:
> ![image](https://user-images.githubusercontent.com/469666/77715656-125c2500-6fd4-11ea-9b44-06488ad244f1.png)

It would be probably best to discuss any such improvements in a separate thread. But, I'll share some thoughts here. 

I'm afraid that by just blindly coloring red would cause too many things red within the diagram. Any error/warning/suggestion is propagated up within the hierarchy. That might cause too many things red and user wouldn't know where to start with. I think there is a need to show the intensity within the navigator. That would be probably combination of size/color. Something like a heatmap. I also see a need for options for different vision modes. Something like in predator movie:
![image](https://www.avpcentral.com/images/predator-vision/thermal-vision.png)
