### ISSUE TITLE
Add the opportunity to see other object produce by or for CRD

### ISSUE THREAD

**Issue by obeyler** [kubevious/kubevious#15]
### Is your feature request related to a problem? Please describe.
Every K8S dashboard have the same lack. They don't show  yaml produced for/by CRD
For example I use traefik V2. I have lot of IngressRoute object but I can not see them
Same case for about all K8S operators I have on my cluster. They can only be listed by kubectlcli

### Describe the solution you'd like
I would be great if by config we can add a list of object type. Then you can show them by a kubectl get XXX or by api call. Another option could also to make a call for each CRD to have the list of object by namespace

**Comment by kubevious** [comment]
@obeyler, we've released a new version that supports custom CRDs. Please see the screenshot below. You can also learn more about other views available in [Kubevious UI Docs](https://kubevious.io/docs/features/application-centric-ui/).

![CleanShot 2022-05-04 at 17 35 24](https://user-images.githubusercontent.com/59004473/166848440-71f7cb91-2c35-4138-a958-f4f540f64a6e.png)

Please try installing again using the latest chart:
```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```
For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).
