### ISSUE TITLE
Disappearing Timeline

### ISSUE THREAD

**Issue by ilknarf** [kubevious/kubevious#17]
### Describe the bug
Timeline won't reappear after clicking "Hide Timeline"

### To Reproduce
1. Go to [demo.kubevious.io](demo.kubevious.io)
2. Click on 'Hide Timeline' under the settings drop-down menu on the top-right corner.
3. Click on 'Show Timeline' under the settings drop-down menu

### Screenshots
![Example](https://user-images.githubusercontent.com/30297768/80897486-c715f000-8cbe-11ea-8120-7db794b891a4.jpg)

### Environment Details:
 - Chrome
 - Kubevious v0.5

**Comment by kubevious** [comment]
Fixed in https://github.com/kubevious/kubevious/releases/tag/v0.6
