### ISSUE TITLE
Feature request - Have some rules already enabled in the default installation

### ISSUE THREAD

**Issue by kostis-codefresh** [kubevious/kubevious#30]
I installed Kubenvious in my cluster and the installation worked fine.

However I found that no rules were defined.

I think that it is best if some rules are already there, so that the user can see the value of the tool right away

I suggest at least the following rules

* public application
* no-resource-limit-pods
* latest-tag-check
* no-memory-request-set

**Comment by rubenhak** [comment]
@kostis-codefresh, thanks for the recommendation.

**Comment by kubevious** [comment]
Resolved in [v0.7](https://github.com/kubevious/kubevious/releases/tag/v0.7).
