### ISSUE TITLE
Creating a marker after a rule does not reset the mark error

### ISSUE THREAD

**Issue by kostis-codefresh** [kubevious/kubevious#31]
### Describe the bug
I created a rule (fat-namespace) without actually having created a marker first. The rule complained that the marker is not present. I added the mark, but the rule was still complaining

### To Reproduce
1. Create a new rule (fat-namespace)
2. Save it
3. See the error message that mark is not present
4. Create mark and save it
5. Rule editor still complains that mark is not there.

### Expected behavior
I expected the rule editor to "refresh" and detect the presence of mark

### Environment Details:
 - Kubernetes Distribution/Version- Azure 1.15.10
 - Browser Firefox
 - Version 0.6.36

**Comment by rubenhak** [comment]
@kostis-codefresh, could you include a screenshot including the error?

Could you please check the screen recording and let us know if you're seeing different behavior?
https://cln.sh/BZ33wF

**Comment by kostis-codefresh** [comment]
I am trying to recreate it again, and I cannot do it a second time. Too bad I did not get a screenshot.

**Comment by rubenhak** [comment]
@kostis-codefresh, we'll keep an eye on it. thanks!
