### ISSUE TITLE
Community Post 

### ISSUE THREAD

**Issue by saiyam1814** [kubevious/kubevious#36]
Do you think adding a section to Readme about the community posts/contributions would be of benefit? 
I wrote a blog recently - https://saiyampathak.com/let-us-take-a-dig-into-kubevious-ckea9d9r700muxhs19jtr3xr8

**Comment by rubenhak** [comment]
@saiyam1814, thanks for the post. What is the format do you think would be best? 
Links including names of authors?

**Comment by kubevious** [comment]
If you think there is a better format please feel free too let us know: https://github.com/kubevious/kubevious#community-posts

**Comment by saiyam1814** [comment]
Yes looks good just created a PR for adding twitter for my name.
