### ISSUE TITLE
Create ClusterIP instead of Nodeport 

### ISSUE THREAD

**Issue by saiyam1814** [kubevious/kubevious#38]
Can we have a clusterIp created instead of Nodeport when installing via helm ?

**Comment by rubenhak** [comment]
we are going to have than on next release

**Comment by saiyam1814** [comment]
Awesome! I am planning to add it to Civo cloud market place will keep kubevious team posted

**Comment by rubenhak** [comment]
Sounds great. Thanks

**Comment by kubevious** [comment]
Resolved in [v0.7](https://github.com/kubevious/kubevious/releases/tag/v0.7).
