### ISSUE TITLE
Helm: Create namespace within the chart.

### ISSUE THREAD

**Issue by kubevious** [kubevious/kubevious#4]
See [https://github.com/kubevious/deploy#standard-deployment](https://github.com/kubevious/deploy#standard-deployment). 

Its currently required to create the namespace separately and then deploy the manifest. It would be great to have a way to eliminate the need to manually create a namespace.

**Comment by rubenhak** [comment]
Resolved: [https://github.com/kubevious/helm](https://github.com/kubevious/helm).
Implemented with helm v3.2
