### ISSUE TITLE
Namespace and K8 Labels as filter

### ISSUE THREAD

**Issue by akshaybhatt14495** [kubevious/kubevious#40]
### Is your feature request related to a problem? Please describe.
Is it possible to have filter on namespace and labels?
User will use some kube context with permission to access only one namespace in that case this might break.
Sometime we need to view only some resources on the basis of labels.

**Comment by rubenhak** [comment]
Wanted to understand better what you would like to achieve. If the users has limited namespace visibility, that would be reflected and only the allowed namespaces would show up in the UI.

What kinds of objects are you more interested? Lets say there is a Ingress with some labels. In Kubevious the Ingress shows up under "Application" node. If you want to filter Ingresses based on labels, would you like to see the Application to which it is associated with? How about other related Application constructs r such as Services, configmaps, etc. Would you like to see them even if they do now have the same labels set?

**Comment by akshaybhatt14495** [comment]
1: Let say we have 4 namespaces Ns1, Ns2, Ns3, Ns4. Now our kubernetes context have some restrictions to access only some set of namespaces let say Ns1. For that reason we want to search resources by providing namespace. within which we can get resources. 

2: Since we are using helm charts for your services. So we are attaching one common label to all resources within a release. For that reason we need a capability to filter by labels. 

Other than this
How is aggregation done at application level? Im curious to know this. Since we are using helm to install. May be we can use similar way to aggregate helm resources together. Or use this service itself. Since it's powerful enough.

**Comment by rubenhak** [comment]
> 1: Let say we have 4 namespaces Ns1, Ns2, Ns3, Ns4. Now our kubernetes context have some restrictions to access only some set of namespaces let say Ns1. For that reason we want to search resources by providing namespace. within which we can get resources.

Only Kubevious Portable uses kube config contexts to connect to clusters (just like the kubectl). The non-portable Kubevious doesn't use contexts. Instead it uses Roles/RoleBindings to request access to the cluster. For non-portable Kubevious you should restrict using RoleBindings instead. 

So assuming you restricted the access to Ns1, then you would not see any other namespace resources, right? 

Is it possible that you have access to multiple namespaces, lets say **Ns1** and **Ns2**, but temporarily want to focus on one namespace at a time, lets say **Ns2** ?

> 2: Since we are using helm charts for your services. So we are attaching one common label to all resources within a release. For that reason we need a capability to filter by labels.

Lets say you have a StatefulSet with label: **foo=bar1**, which uses ConfigMap **foo=bar1**. Now you change the value to **bar2**. StatefulSet doesn't let you modify the label, and so it stays **bar1** for the StatefulSet but changes to **bar2** for the ConfigMap.

So if the filter criteria is  **foo=bar2** then the StatefulSet wouldn't show up in the diagram, and its child ConfigMap wouldn't show up as well. 

Filtering based on labels is bit tricky within the diagram. We could probably do a label search similar to the "Search" where you would see flat list of objects that match the filters. Clicking on the search result would navigate to the diagram.

> How is aggregation done at application level? Im curious to know this. Since we are using helm to install. May be we can use similar way to aggregate helm resources together. Or use this service itself. Since it's powerful enough.

Its done based on labels, ports, selectors and other metadata within the specs. No, I think you shouldn't change the way you deploy your apps. It kind of contradicts to fundamental principles of the project :)

**Comment by kubevious** [comment]
Support added in [v0.8](https://github.com/kubevious/kubevious/releases/tag/v0.8)
