### ISSUE TITLE
Define log level on deployment

### ISSUE THREAD

**Issue by kfirfer** [kubevious/kubevious#41]
Hello

Would be nice to have ability to set the log level of each component
warning/error/info/debug etc...

Im using helm chart version: 
0.7.18

**Comment by rubenhak** [comment]
hi @kfirfer, what is your use case? are you seeing too much logs? 
by saying component are you referring to pods, or individual components of the process?

**Comment by kfirfer** [comment]
Yes its printing a lot of logs, hard to trace problems
Referring to the processes under the hood, its could be on the pod/deployment level as-well

**Comment by rubenhak** [comment]
Yes, we can add that. Any other issue you had that you were trying to debug?
Also, on which pod do you see much logs? kubevious? parser?

**Comment by kfirfer** [comment]
**Yes, we can add that. Any other issue you had that you were trying to debug?**
Not that I came up with


**Also, on which pod do you see much logs? kubevious? parser?**
Both of them, they equally print the same amount of logs

**Comment by kubevious** [comment]
Support added in [v0.8](https://github.com/kubevious/kubevious/releases/tag/v0.8)
