### ISSUE TITLE
Installing on Openshift 3.11

### ISSUE THREAD

**Issue by MastanaGuru** [kubevious/kubevious#43]
I am trying to install on openshift 3.11, but the kubevious-ui pod fails to start with below exceptions
```
sed: can't create temp file '/etc/nginx/conf.d/default.confXXXXXX': Permission denied
--
  | sed: can't create temp file '/etc/nginx/conf.d/default.confXXXXXX': Permission denied
  | 2020/10/04 23:01:19 [warn] 11#11: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
  | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
  | 2020/10/04 23:01:19 [emerg] 11#11: host not found in resolver "$DNS_SERVERS" in /etc/nginx/conf.d/default.conf:12
  | nginx: [emerg] host not found in resolver "$DNS_SERVERS" in /etc/nginx/conf.d/default.conf:12
```
 
Any documentation on openshift 3.11 installation ?

**Comment by kubevious** [comment]
@MastanaGuru, we are using the following docker-entrypoint.sh script to setup nginx reverse proxy:

```sh
#!/usr/bin/env sh

sed -i -r 's~\$BACKEND_URL~'"${BACKEND_URL}"'~g' /etc/nginx/conf.d/default.conf

DNS_SERVERS=$(awk 'BEGIN{ORS=" "} $1=="nameserver" {print $2}' /etc/resolv.conf)
sed -i -r 's~\$DNS_SERVERS~'"${DNS_SERVERS}"'~g' /etc/nginx/conf.d/default.conf

nginx -g "daemon off;"
```

This was not tested with OpenShift. Could you check if you have any security policies that would prevent the script from writing into **/etc/nginx/conf.d/default.conf** file?

**Comment by kubevious** [comment]
@MastanaGuru, Thanks for reporting the issue. We have just released a new version and replaced NGINX with Caddy. That path is no longer modified by Kubevious, so should not hit a permission issue on OpenShift.

Please try installing again using the latest chart and let us know how it works.

```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```
For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).
