### ISSUE TITLE
External name service is not treated properly - 

### ISSUE THREAD

**Issue by derrickburns** [kubevious/kubevious#47]
Kubevious reports "Could not find apps matching selector" for ExternalName Service. This is incorrect.

**Comment by rubenhak** [comment]
@derrickburns, could you provide and example config for such service?

**Comment by derrickburns** [comment]
apiVersion: v1
kind: Service
metadata:
  annotations:
    fluxcd.io/sync-checksum: 8c03fabae09f1fe23679ffe4418acb2bb0f6d8ff
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"fluxcd.io/sync-checksum":"8c03fabae09f1fe23679ffe4418acb2bb0f6d8ff"},"labels":{"app":"zk-1","fluxcd.io/sync-gc-mark":"sha256.T0kFKDum-PVrsTZKHowsyEuDQxrWP3Fxwke3CH9vMTQ"},"name":"zk-1","namespace":"amazon"},"spec":{"externalName":"z-1.ops-default.ccpe21.c4.kafka.us-west-2.amazonaws.com","ports":[{"port":2181,"protocol":"TCP","targetPort":2181}],"selector":{"app":"zk-1"},"type":"ExternalName"}}
  creationTimestamp: "2020-07-05T04:37:23Z"
  labels:
    app: zk-1
    fluxcd.io/sync-gc-mark: sha256.T0kFKDum-PVrsTZKHowsyEuDQxrWP3Fxwke3CH9vMTQ
  name: zk-1
  namespace: amazon
  resourceVersion: "196439802"
  selfLink: /api/v1/namespaces/amazon/services/zk-1
  uid: e23f9ad0-78b8-4910-973e-fc39f9e9bd42
spec:
  externalName: z-1.ops-default.ccpe21.c4.kafka.us-west-2.amazonaws.com
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zk-1
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}

**Comment by rubenhak** [comment]
@derrickburns, I though for ExternalName services the "selector" should not be specified. Nevertheless, we can ignore selector for ExternalName services

**Comment by derrickburns** [comment]
Thanks!

**Comment by kubevious** [comment]
Resolved in [v0.7](https://github.com/kubevious/kubevious/releases/tag/v0.7).
