### ISSUE TITLE
Helm: Repository & Release based installation

### ISSUE THREAD

**Issue by kubevious** [kubevious/kubevious#5]
See [https://github.com/kubevious/deploy](https://github.com/kubevious/deploy).

Kubevious is currently installed by templating helm charts and applying the manifest using kubectl.

Make the chart also installable using "helm install" so that there is no need to "git clone" the repo to install Kubevious.

**Comment by rubenhak** [comment]
Resolved in v0.4: [https://github.com/kubevious/helm](https://github.com/kubevious/helm)
