### ISSUE TITLE
Error 502 upon installation through helm

### ISSUE THREAD

**Issue by run-stop** [kubevious/kubevious#56]
### Describe the bug
I'm installing Kubevious as described at the GitHub homepage using my in house kubernetes cluster. Once the installation is over I'm starting the kube proxy to access the application. The application starts loading, but on the top of the screen I'm getting the error message: `"Error occurred: <!DOCTYPE html> <html> <head> <title>Error</title> <style> body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; } </style> </head> <body> <h1>An error occurred.</h1> <p>Sorry, the page you are looking for is currently unavailable.<br/> Please try again later.</p> <p>If you are the system administrator of this resource then you should check the error log for details.</p> <p><em>Faithfully yours, nginx.</em></p> </body> </html>"`

### To Reproduce
1. `kubectl create namespace kubevious`
2. `helm repo add kubevious https://helm.kubevious.io`
3. `helm upgrade --atomic --set mysql.persistence.storageClass=managed-nfs-storage -i kubevious kubevious/kubevious --version 0.8.15 -n kubevious --reuse-values`
4. `kubectl port-forward $(kubectl get pods -n kubevious -l "app.kubernetes.io/component=kubevious-ui" -o jsonpath="{.items[0].metadata.name}") 8080:80 -n kubevious`
5. Go to `http://localhost:8080/` using the web browser to see the "502:..." error.

### Expected behavior
Besides the 502 error, all the panels are empty. I have followed the instructions carefully with the exception of creating the NFS storage class. It should be working.

### Environment Details:
 - Kubernetes version: {Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rubenhak** [comment]
@run-stop, can you check if the **kubevious** pod is healthy. Also please check the logs. If there is an issue with the storage, then the mysql wouldn't come up properly, and that would not let **kubevious** pod to be ready. Also, please check the mysql logs.

**Comment by run-stop** [comment]
@rubenhak, thank you very much for your help. The problem was infrastructure-related. I've started digging through my (complex home) environment and had to adjust the DNS server IP address assigned to the VLAN clients. This VLAN is where my Kubernetes nodes are sitting. So the DNS IP  was not reachable from the coredns pod, and this caused Kubevious to misbehave.
Once I fixed that, the application is running like a charm!

I believe we can close this issue.

**Comment by rubenhak** [comment]
@run-stop, great that it worked! 

I wanted to get some feedback from you. Would you mind joining our slack channel to have a quick discussion? [https://kubevious.io/slack](https://kubevious.io/slack)

Thanks,
Ruben

**Comment by run-stop** [comment]
Hi Ruben,

I just signed in to the Slack channel.

**Comment by rubenhak** [comment]
awesome, talk to you there. closing this issue.
