### ISSUE TITLE
"logger" undefined if kubevious.log.level changed from default

### ISSUE THREAD

**Issue by mozai** [kubevious/kubevious#57]
### Describe the bug
logger is missing if I change the loglevel in the helmchart

### To Reproduce
1. kubectl create namespace kubevious
2. `echo 'kubevious: {log: {level: warning}}' >values.yaml`  (EDIT: fixed typo)
3. `helm upgrade --atomic --install kubevious --namespace kubevious kubevious/kubevious --version 0.8.15 --debug --values values.yaml`

### Expected behavior
Kubevious is deployed with less noise in the logs, or an error message about an inappropriate string in the config file i.e. "no such log level 'warning' "

### Unexpected behaviour
    $ kubectl --namespace kubevious logs -c kubevious --tail 1000 --previous kubevious-744ffb8f78-zk84p
    /app/node_modules/@kubevious/helper-backend/dist/backend.js:94
            this.logger.error('[_uncaughtException] Reason: ', reason);
                        ^
    
    TypeError: Cannot read property 'error' of undefined
        at Backend._uncaughtException (/app/node_modules/@kubevious/helper-backend/dist/backend.js:94:21)
        at process.emit (events.js:314:20)
        at process._fatalException (internal/process/execution.js:165:25)

### Environment Details:
 - Kubernetes: 1.18.20
 - Helm: 3.3.0
 - Browser: n/a
 - Version: 0.8.15

**Comment by rubenhak** [comment]
hi @mozai,  try using `warn` instead of `warning` in the yaml file. 
I also assume that there is a typo while posting this issue in the step 2.

**Comment by mozai** [comment]
Where can we find a list of valid strings for the "kubevoius.log.level" parameter?  Maybe this is a documentation problem.

**Comment by rubenhak** [comment]
@mozai, the list of log severities is here: [https://github.com/kubevious/helm#configuration](https://github.com/kubevious/helm#configuration), scroll down to *kubevious.log.level* row.
