### ISSUE TITLE
Error: release kubevious failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

### ISSUE THREAD

**Issue by maorkuriel** [kubevious/kubevious#59]
### Describe the bug
I am trying to run the tool on Minikube on my Macbook pro M1 and failing to install it with an error message 
❯ helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.8.15 -n kubevious

Release "kubevious" does not exist. Installing it now.
Error: release kubevious failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

~ took 5m3s
### To Reproduce
~ took 25s
❯ kubectl create namespace kubevious

namespace/kubevious created

~
❯ helm repo add kubevious https://helm.kubevious.io

"kubevious" has been added to your repositories

~ took 2s
❯ helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.8.15 -n kubevious

Release "kubevious" does not exist. Installing it now.
Error: release kubevious failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

### Expected behavior
A running Kubevious system up and running
 
### Environment Details:
MacBook Pro M1
❯ minikube start
😄  minikube v1.23.2 on Darwin 12.0.1 (arm64)
🎉  minikube 1.24.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.24.0
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                      │
│    Registry addon with docker driver uses port 54143 please use that instead of default port 5000    │
│                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
📘  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
    ▪ Using image registry:2.7.1
    ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
🔎  Verifying registry addon...
🌟  Enabled addons: storage-provisioner, default-storageclass, registry
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Comment by rubenhak** [comment]
@maorkuriel, lets try adding `--debug` argument to helm upgrade, and also removing the `--atomic` flag. One of the components is not coming up properly. The chart also installs mysql with PVCs. One of the common issues is coming up from there.

Please include more details from helm install and pods that are failing.

**Comment by maorkuriel** [comment]
Hi @rubenhak  
I ran the helm upgrade as you instructed here is the output:
❯ helm upgrade -i kubevious kubevious/kubevious --version 0.8.15 -n kubevious --debug

history.go:56: [debug] getting history for release kubevious
Release "kubevious" does not exist. Installing it now.
install.go:178: [debug] Original chart version: "0.8.15"
install.go:199: [debug] CHART PATH: /Users/maorkuriel/Library/Caches/helm/repository/kubevious-0.8.15.tgz

client.go:128: [debug] creating 16 resource(s)
NAME: kubevious
LAST DEPLOYED: Wed Dec 15 10:02:02 2021
NAMESPACE: kubevious
STATUS: deployed
REVISION: 1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
cluster:
  domain: cluster.local
fullnameOverride: ""
ingress:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  enabled: false
  hosts:
  - host: ""
    paths:
    - ""
  tls: []
kubevious:
  affinity: {}
  image:
    pullPolicy: IfNotPresent
    repository: kubevious/kubevious
    tag: 0.8.20
  imagePullSecrets: []
  log:
    level: info
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  securityContext: {}
  service:
    port: 4001
    type: ClusterIP
  tolerations: []
mysql:
  affinity: {}
  db_name: kubevious
  db_password: ""
  db_user: kubevious
  external:
    database: ""
    enabled: false
    host: ""
    password: ""
    port: ""
    user: ""
  generate_passwords: false
  image:
    pullPolicy: IfNotPresent
    repository: mysql
    tag: 8.0.22
  imagePullSecrets: []
  nodeSelector: {}
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 10Gi
    storageClass: ""
  podAnnotations: {}
  podSecurityContext: {}
  resources:
    requests:
      cpu: 250m
      memory: 1000Mi
  root_password: ""
  securityContext: {}
  service:
    port: "3306"
    type: ClusterIP
  tolerations: []
nameOverride: ""
parser:
  affinity: {}
  image:
    pullPolicy: IfNotPresent
    repository: kubevious/parser
    tag: 0.8.15
  imagePullSecrets: []
  log:
    level: info
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  securityContext: {}
  service:
    port: 4002
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
ui:
  affinity: {}
  image:
    pullPolicy: IfNotPresent
    repository: kubevious/ui
    tag: 0.8.13
  imagePullSecrets: []
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources:
    requests:
      cpu: 25m
      memory: 50Mi
  securityContext: {}
  service:
    port: 80
    type: ClusterIP
  tolerations: []
worldvious:
  opt_out_all: false
  opt_out_counters_report: false
  opt_out_error_report: false
  opt_out_metrics_report: false
  opt_out_version_check: false

HOOKS:
---
# Source: kubevious/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "kubevious-test-connection"
  labels:
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['kubevious:4001']
  restartPolicy: Never
MANIFEST:
---
# Source: kubevious/templates/parser/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevious-parser
  labels:
    app.kubernetes.io/component: kubevious-parser
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
---
# Source: kubevious/templates/mysql/secret-root.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubevious-mysql-secret-root
  labels:
    app.kubernetes.io/component: kubevious-mysql
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "a3ViZXZpb3Vz"
---
# Source: kubevious/templates/mysql/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubevious-mysql-secret
  labels:
    app.kubernetes.io/component: kubevious-mysql
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  MYSQL_PASS: "a3ViZXZpb3Vz"
---
# Source: kubevious/templates/worldvious/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubevious-worldvious
  labels:
    app.kubernetes.io/component: kubevious
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  WORLDVIOUS_ID: "ZDc5M2JhYWMtMzA2YS00MTFjLTk1OGQtNGY2MTFjMTA1YmE4"
---
# Source: kubevious/templates/mysql/configmap-db.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevious-mysql-conf
  labels:
    app.kubernetes.io/component: kubevious-mysql
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
---
# Source: kubevious/templates/mysql/configmap-init-script.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevious-mysql-init-script
  labels:
    app.kubernetes.io/component: kubevious-mysql
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
data:
  initdb.sql: |
    USE kubevious;

    SET NAMES utf8;
---
# Source: kubevious/templates/worldvious/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevious-worldvious
  labels:
    app.kubernetes.io/component: kubevious
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
data:
  WORLDVIOUS_URL: https://api.kubevious.io/api/v1/oss
---
# Source: kubevious/templates/parser/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevious-parser
  labels:
    app.kubernetes.io/component: kubevious-parser
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
rules:

  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
      - configmaps
      - pods
      - nodes
      - limitranges
      - serviceaccounts
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
---
# Source: kubevious/templates/parser/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevious-parser
  labels:
    app.kubernetes.io/component: kubevious-parser
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevious-parser
subjects:
- kind: ServiceAccount
  name: kubevious-parser
  namespace: kubevious
---
# Source: kubevious/templates/kubevious/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: kubevious
  labels:
    app.kubernetes.io/component: kubevious
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: kubevious
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
---
# Source: kubevious/templates/mysql/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: kubevious-mysql
  labels:
    app.kubernetes.io/component: kubevious-mysql
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/component: kubevious-mysql
---
# Source: kubevious/templates/ui/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: kubevious-ui-clusterip
  labels:
    app.kubernetes.io/component: kubevious-ui
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: kubevious-ui
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
---
# Source: kubevious/templates/kubevious/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevious
  labels:
    app.kubernetes.io/component: kubevious
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubevious
      app.kubernetes.io/name: kubevious
      app.kubernetes.io/instance: kubevious
      app.kubernetes.io/managed-by: Helm
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubevious
        app.kubernetes.io/name: kubevious
        app.kubernetes.io/instance: kubevious
        helm.sh/chart: kubevious-0.8.15
        app.kubernetes.io/version: "0.8.15"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: kubevious
          securityContext:
            {}
          image: "kubevious/kubevious:0.8.20"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: MYSQL_HOST
              value: "kubevious-mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB
              value: "kubevious"
            - name: MYSQL_USER
              value: "kubevious"
          envFrom:
            - configMapRef:
                name: kubevious-worldvious
            - secretRef:
                name: kubevious-mysql-secret
            - secretRef:
                name: kubevious-worldvious
          ports:
            - name: http
              containerPort: 4001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
---
# Source: kubevious/templates/parser/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevious-parser
  labels:
    app.kubernetes.io/component: kubevious-parser
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubevious-parser
      app.kubernetes.io/name: kubevious
      app.kubernetes.io/instance: kubevious
      app.kubernetes.io/managed-by: Helm
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubevious-parser
        app.kubernetes.io/name: kubevious
        app.kubernetes.io/instance: kubevious
        helm.sh/chart: kubevious-0.8.15
        app.kubernetes.io/version: "0.8.15"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: kubevious-parser
      securityContext:
        {}
      containers:
        - name: kubevious
          securityContext:
            {}
          image: "kubevious/parser:0.8.15"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: KUBEVIOUS_COLLECTOR
              value: "http://kubevious.kubevious.svc.cluster.local:4001/api/v1/collect"
          envFrom:
            - configMapRef:
                name: kubevious-worldvious
            - secretRef:
                name: kubevious-worldvious
          ports:
            - name: http
              containerPort: 4002
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
---
# Source: kubevious/templates/ui/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevious-ui
  labels:
    app.kubernetes.io/component: kubevious-ui
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubevious-ui
      app.kubernetes.io/name: kubevious
      app.kubernetes.io/instance: kubevious
      app.kubernetes.io/managed-by: Helm
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubevious-ui
        app.kubernetes.io/name: kubevious
        app.kubernetes.io/instance: kubevious
        helm.sh/chart: kubevious-0.8.15
        app.kubernetes.io/version: "0.8.15"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: kubevious
          securityContext:
            {}
          image: "kubevious/ui:0.8.13"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: BACKEND_URL
              value: "kubevious.kubevious.svc.cluster.local:4001"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
---
# Source: kubevious/templates/mysql/statefulset.yaml
# source: https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubevious-mysql
  labels:
    app.kubernetes.io/component: kubevious-mysql
    app.kubernetes.io/name: kubevious
    app.kubernetes.io/instance: kubevious
    helm.sh/chart: kubevious-0.8.15
    app.kubernetes.io/version: "0.8.15"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: kubevious-mysql
      app.kubernetes.io/name: kubevious
      app.kubernetes.io/instance: kubevious
      app.kubernetes.io/managed-by: Helm
  serviceName: kubevious-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubevious-mysql
        app.kubernetes.io/name: kubevious
        app.kubernetes.io/instance: kubevious
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      initContainers:
      - name: init-mysql
        image: mysql:8.0.22
        command:
        - bash
        - "-c"
        - |
          set -ex
          echo "[mysqld]" > /mnt/conf.d/server-id.cnf
          echo "server-id=1" >> /mnt/conf.d/server-id.cnf
          echo "[mysqld]" > /mnt/conf.d/bin-logs.cnf
          echo "binlog_expire_logs_seconds=259200" >> /mnt/conf.d/bin-logs.cnf
          cp /mnt/config-map/master.cnf /mnt/conf.d/
        volumeMounts:
        - name: conf
          mountPath: /mnt/conf.d
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - name: mysql
        image: "mysql:8.0.22"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MYSQL_DATABASE
          value: "kubevious"
        - name: MYSQL_USER
          value: "kubevious"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubevious-mysql-secret
              key: MYSQL_PASS
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubevious-mysql-secret-root
              key: MYSQL_ROOT_PASSWORD
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: "data"
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command:
              - bash
              - "-c"
              - |
                mysql -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e 'SELECT 1'
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        resources:
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: kubevious-mysql-conf
      - name: init-script
        configMap:
          name: kubevious-mysql-init-script
  volumeClaimTemplates:
  - metadata:
      name: "data"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

NOTES:
NKXW
                                                           WXx:,;oKW
                                                          Nk;.....,oKW
                                                          No'.......,oKW
                                                           Nkc'.......,o0W
                                                        WKxkNNkc'.......,oKW
                                                        Kc.'ckNNkc'.......,oKW
                                    WWWNNNNWW          Nk;...'ckNNkc'.......cK
                              WX0kdocc:::::clodk0NW  NOc'......'ckNNkc'...'cON
                           N0dc;'...............:ONNOc'..........'ckNNkl:ckN
                        WKx:'.................'c0WKl'...........,,;oX  WNW
                      WKd;.....................;d0X0d;........;d0KXW
                     Nk:.........................'ckXKx;....;xXW
                    Xd,............................':kXKo,:xXW
                   Xo'...............................'l0NKXNXW
                  Wd'..................................;kXOc:O
                  Nkooooooooooooooooooooooooooooooooooooxkdod0W
             WNK0000000000000000000000000000000000KK0000KKK0000KKXW
             Kl,''''''''''''''''''''''''''''''''''''''''''''''''';xW
             NkdoooooooooooooooooooooooooooooooooooooooooooooooooxKW
                WNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNW
                Nd,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,dN
                Nl....................''''....................oN
                Nl................';ok000Oko;.................oN
                Nl...............'oXWKkxxkKWXo'...............oN
                Nl...............lXWO;....;kWXl...............oN
                Nl..............'dWWd'.....lNWd'.............'oN
                WKOkkkkkkkkkkkkkOXWWKOkkkkkKW XOOOOOOOOOOOOOOOKW

Kubevious v0.8.15 installed!
Access Kubevious by setting up port forwarding
 


But When I navigate to http://127.0.0.1:8080 I am getting error 500

<img width="1076" alt="Screen Shot 2021-12-15 at 10 05 37" src="https://user-images.githubusercontent.com/32849081/146147401-478bd76f-8fba-41bc-a79c-dd5b6283bf1a.png">

**Comment by rubenhak** [comment]
@maorkuriel, did you check "kubevious" Deployment and the "kubevious-mysql" StatefulSet? Are the corresponding pods up and running? Are they ready? Any errors in the logs?

**Comment by maorkuriel** [comment]
@rubenhak  They were running. I will spin up another deployment and test it again.

**Comment by rubenhak** [comment]
@maorkuriel, that's odd. There is not much information for me to troubleshoot. Want to have a live call to debug? I've sent you an invite on LinkedIn.

**Comment by kubevious** [comment]
@maorkuriel, we've released a new version that could resolve this issue. Could you please give it a try and reopen the issue if it still persists.

```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```
For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).
