### ISSUE TITLE
Backend: Gracefully handing parsing errors

### ISSUE THREAD

**Issue by kubevious** [kubevious/kubevious#6]
Gracefully handle parsing errors. Currently because of a single error nothing would render on the screen. 

Need something smarter than try/catch. Accumulate exceptions. Deduplicate exceptions. Generate report including which parsers failed, on which objects. Include details on which objects the parsing failed. Best if a package is downloadable from UI.

Even better if a button appears on a UI with the bug details prefilled. Instructions on prefilling bugs in github here: [https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters](https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters)

```
File: src/lib/logic/processor.js
Function: _processHandler
Line: 232: handlerInfo.handler(handlerArgs);
```

**Comment by rubenhak** [comment]
Resolved in v0.3
