### ISSUE TITLE
Can you please provide the steps to install kubevious to Kubernetes cluster using kubectl instead of using helm

### ISSUE THREAD

**Issue by baoquach14** [kubevious/kubevious#60]
Can you please provide the steps to install kubevious to Kubernetes cluster using kubectl instead of using helm.

I am getting an error when running  "helm repo add kubevious https://helm.kubevious"
Error: looks like "https://helm.kubevious.io" is not a valid chart repository or cannot be reached:
connect: connection timed out

Thank you for your help

**Comment by kubevious** [comment]
Thanks for reporting the issue. Sorry for the late response. Helm chart should be the right way to deploy Kubevious. There was probably a momentary glitch with the web hosting causing the helm public repo [https://helm.kubevious.io/](https://helm.kubevious.io/) not to being accessible. 

Please try installing again using the latest chart:
```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```
For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).

If you still need to get the YAML manifest to deploy Kubevious without Helm, here are the instructions to do that:
```
$ git clone https://github.com/kubevious/helm.git kubevious-helm.git
$ cd kubevious-helm.git
$ helm template kubevious ./kubernetes -n kubevious --output-dir output/
$ kubectl apply -f output/ --recursiv
```
