### ISSUE TITLE
rule 'no-resource-limits-pods' has typo

### ISSUE THREAD

**Issue by hiondal** [kubevious/kubevious#61]
### Describe the bug
The condition of rule 'no-resource-limits-pods' is '!container.resources.limit'. 
but, It should be '!container.resources.limits' as followed. 
You omit 's' at 'limit'. 
for(var container of item.config.spec.containers)
{
  if (!container.resources.limits)
  {
    warning('No resource limit set');
  }
}

### Environment Details:
 - Kubernetes Distribution/Version [e.g. GKE v1.13.12-gke.25, OpenShift 4.3]
 - Version [e.g. v0.3]

**Comment by kubevious** [comment]
Thanks for reporting. This issue has been resolved in the latest version 🎉🎉🎉.
Please let us know how it works!

```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```

For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).
