### ISSUE TITLE
missing ServiceAccount for redis

### ISSUE THREAD

**Issue by christianknell** [kubevious/kubevious#70]
In the current version of the Chart (1.0.3) there is no ServiceAccount defined for redis, but there exists a value in values.yaml and also a helper-function to define the name for ServiceAccount.

**Comment by kubevious** [comment]
@tanmay-bhat, thanks for providing the fix.

@christianknell, please try it out and lets us know if it works for you:
```
helm upgrade --atomic -i kubevious kubevious/kubevious --version 1.0.4 -n kubevious 
```

**Comment by christianknell** [comment]
@kubevious works as expected. Thanks!
