### ISSUE TITLE
Where's the open source code for Kubevious? 

### ISSUE THREAD

**Issue by pcgeek86** [kubevious/kubevious#77]
According to the Kubevious website, this is an open source project. However, the website links to this repository, which doesn't actually contain any application source code. Is Kubevious truly open source? 🤔

**Comment by tanmay-bhat** [comment]
Hey @pcgeek86 , I believe all available code you're looking for is [here](https://github.com/kubevious?tab=repositories).

Moreover, @rubenhak I hope can clarify if you have any additional doubts over this.

**Comment by rubenhak** [comment]
Thanks @tanmay-bhat.

@pcgeek86, the project is indeed open-source. Unlike many other "cli tools", it was very hard and impractical to fit all the code into a single repository. There are 4 executables and numerous modules involved. Please see the [CONTRIBUTING  guide](https://github.com/kubevious/kubevious/blob/master/CONTRIBUTING.md#where-is-the-stuff) for the locations of the source code.

Btw, we are looking for maintainers to help driving the project. There are lots of things to do. If you want to learn more feel free to join the [weekly community meeting](https://www.meetup.com/kubevious/) or reach out on [slack channel](https://kubevious.io/slack)
