### ISSUE TITLE
Make Kubevious Rules a CRD

### ISSUE THREAD

**Issue by rawkode** [kubevious/kubevious#78]
### Is your feature request related to a problem? Please describe.
I'd like my Kubevious rules to be applied in a GitOps fashion

**Comment by kubevious** [comment]
@rawkode, thank you for submitting this request!

The Kubevious CLI loads rules from multiple sources: Git Repos, web links, and CRDs. 
[https://github.com/kubevious/cli](https://github.com/kubevious/cli)
