### ISSUE TITLE
GUARD: Run command of generate manifest.yaml

### ISSUE THREAD

**Issue by lesmyrmidons** [kubevious/kubevious#82]
### Describe the bug
the script use `jq`. Step `Parsing Input...`, an error return  `ERROR: Malformed YAML streamed` and a message  :
 ```
jq: Unknown option -o
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

### To Reproduce
1. version `jq` used : 1.6
2. run command : `cat manifests.yaml | sh <(curl -sfL https://run.kubevious.io/validate.sh)`

### Environment Details:
 - Manjaro:  22.1.0 Talos
 - jq: 1.6
 - zsh
 - kubectl: v1.26.3
 - go: 1.19.7

**Comment by rubenhak** [comment]
@lesmyrmidons, the validation script is replaced by a dedicated CLI tool. It is more robust, uses revised rules engine and library, and integrates much better with CI/CD pipelines. The script you used is going to be retired. 
Please try this out: 
https://github.com/kubevious/cli
