### ISSUE TITLE
validate.sh converts \" -> " which causes yq to fail

### ISSUE THREAD

**Issue by mike-prefix** [kubevious/kubevious#92]
### Describe the bug
Right now validate.sh
does 
while read line; do
...

which will convert an input line like 
oauth2_proxy.cfg: "email_domains = [ \"*\" ]\nupstreams = [ \"file:///dev/null\" ]"
to 
oauth2_proxy.cfg: "email_domains = [ "*" ]nupstreams = [ "file:///dev/null" ]"

which is not valid yaml so yq complains.

### To Reproduce
The following yaml will trigger the error (its from the oauth2-proxy helm chart) : 

# Source: oauth2-proxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: oauth2-proxy
    helm.sh/chart: oauth2-proxy-7.7.8
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/version: 7.6.0
  name: oauth2-proxy
  namespace: base
data:
  oauth2_proxy.cfg: "email_domains = [ \"*\" ]\nupstreams = [ \"file:///dev/null\" ]"

cat snippet.yaml | sh <(curl -sfL https://run.kubevious.io/validate.sh)
gives 

**** KUBEVIOUS CHANGE VALIDATOR ****

👉 *** Reading Input...
✅     Reading Input. Done.
👉 *** Parsing Input...
Input Length: 545
Error: bad file '-': yaml: line 16: did not find expected alphabetic or numeric character
🔴🔴🔴
🔴🔴🔴 ERROR: Malformed YAML streamed
🔴🔴🔴

This is the line from above.

### Expected behavior
It should parse fine.

I think s/read line/read -r line/ should fix it (or does in this case)

### Environment Details:
yq (https://github.com/mikefarah/yq/) version v4.44.2
Macos

### Additional context
I think s/read line/read -r line/ should fix it (or does in this case)

Thanks!!

**Comment by mike-prefix** [comment]
Ooof the backslashes from above seem to be formatting in github

![CleanShot 2024-08-19 at 13 34 51@2x](https://github.com/user-attachments/assets/6c2b96c1-6228-42dd-93ce-7338678c5f8f)

**Comment by rubenhak** [comment]
hi @mike-tempco, the `https://run.kubevious.io/validate.sh` is the legacy validator which is not supported anymore. 

Please use the standalone Kubevious CLI for validation. It is much more powerful and easier to use. Please check it out and fell free to let me know if you need additional help:
[https://github.com/kubevious/cli](https://github.com/kubevious/cli)

**Comment by mike-prefix** [comment]
Ahh, thanks!  Sorry for the spam.  Will use the cli

**Comment by rubenhak** [comment]
@mike-tempco, no worries. Feel free to reach out. Closing this issue for now.
